[tox]
envlist = py3
skip_missing_interpreters = True

[testenv]
deps =
    mypy
    pyjwt
    pytest
    ratelimit
    requests
    requests_mock
    types-requests
commands =
    pytest -q
    python -m mypy pyflumeng
    python scripts/generate_api_reference.py --check
    python -m compileall -q pyflumeng
