"""PyFlumeNG: a complete Flume API client with portal capabilities."""

from .auth import (  # noqa: WPS300, F401
    FlumeAuth,
    FlumePortalAuth,
)
from .auth import (
    FlumeAuth as PersonalAuth,
)
from .auth import (
    FlumePortalAuth as PortalAuth,
)
from .client import FlumeClient  # noqa: WPS300, F401
from .data import FlumeData  # noqa: WPS300, F401
from .devices import FlumeDeviceList  # noqa: WPS300, F401
from .errors import (  # noqa: WPS300, F401
    FlumeAuthError,
    FlumeCapabilityError,
    FlumeError,
    FlumeHTTPError,
    FlumeRateLimitError,
)
from .leak import FlumeLeakList  # noqa: WPS300, F401
from .models import (  # noqa: WPS300, F401
    AccuracyResult,
    ApiClient,
    Budget,
    Contact,
    CurrentFlow,
    Device,
    DoNotAlertSchedule,
    FlumeModel,
    FlumeResponse,
    Insurer,
    Integration,
    Leak,
    Location,
    LocationAccess,
    LocationFeatures,
    LocationProfile,
    LocationProfiles,
    Notification,
    NotificationExtra,
    NotificationQuery,
    ProService,
    PurchaseOption,
    QueryResult,
    RecurrenceRule,
    Span,
    SpanDataPoint,
    SpanType,
    Subscription,
    UsageAlert,
    UsageAlertRule,
    UsageAlertSchedule,
    UsageBreakdown,
    UsageBreakdownCategory,
    User,
    UserPlan,
)
from .notifications import FlumeNotificationList  # noqa: WPS300, F401
from .rate_limit import RateLimitState  # noqa: WPS300, F401
from .usage import FlumeUsageAlertList  # noqa: WPS300, F401

__all__ = [
    "FlumeAuth",
    "PersonalAuth",
    "FlumePortalAuth",
    "PortalAuth",
    "FlumeClient",
    "FlumeData",
    "FlumeDeviceList",
    "FlumeLeakList",
    "FlumeNotificationList",
    "FlumeUsageAlertList",
    "FlumeModel",
    "FlumeResponse",
    "User",
    "Device",
    "Location",
    "LocationFeatures",
    "LocationProfile",
    "LocationProfiles",
    "Notification",
    "NotificationExtra",
    "NotificationQuery",
    "UsageAlert",
    "UsageAlertRule",
    "UsageAlertSchedule",
    "UsageBreakdown",
    "UsageBreakdownCategory",
    "UserPlan",
    "Budget",
    "Subscription",
    "DoNotAlertSchedule",
    "RecurrenceRule",
    "LocationAccess",
    "Integration",
    "Span",
    "SpanDataPoint",
    "SpanType",
    "Leak",
    "CurrentFlow",
    "QueryResult",
    "PurchaseOption",
    "Contact",
    "Insurer",
    "ApiClient",
    "AccuracyResult",
    "ProService",
    "RateLimitState",
    "FlumeError",
    "FlumeAuthError",
    "FlumeCapabilityError",
    "FlumeHTTPError",
    "FlumeRateLimitError",
]
